In [1]:
import numpy as np

X = np.random.rand(4, 3)
D, P = np.linalg.eig(X.T @ X)
sort_idx = D.argsort()[::-1]
D = D[sort_idx]
P = P[:,sort_idx]
P = X @ P
P = P / np.linalg.norm(P, axis=0)
print(P)

U, S, V = np.linalg.svd(X, full_matrices=False)
print(U)

[[ 0.62860633  0.21103595 -0.67370021]
 [ 0.3813152  -0.04173899  0.65701236]
 [ 0.36373949  0.71872547  0.32438502]
 [ 0.57196711 -0.66117727  0.09611003]]
[[-0.62860633  0.21103595  0.67370021]
 [-0.3813152  -0.04173899 -0.65701236]
 [-0.36373949  0.71872547 -0.32438502]
 [-0.57196711 -0.66117727 -0.09611003]]
